# Generated by Django 5.2.3 on 2025-06-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_staticpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Описание страницы (до 160 символов)', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы (до 60 символов)', max_length=60, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Описание страницы (до 160 символов)', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы (до 60 символов)', max_length=60, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Описание страницы (до 160 символов)', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы (до 60 символов)', max_length=60, verbose_name='Meta Title'),
        ),
    ]
