# Generated by Django 5.2.3 on 2025-06-29 10:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_block', ckeditor.fields.RichTextField(blank=True, verbose_name='Текстовый блок подвала')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки подвала',
                'verbose_name_plural': 'Настройки подвала',
            },
        ),
    ]
