# Generated by Django 5.2.3 on 2025-06-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='is_active',
        ),
    ]
