# Generated by Django 5.2.3 on 2025-06-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_email_alter_order_name_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='new', max_length=16, verbose_name='Статус'),
        ),
    ]
