# Generated by Django 5.2.3 on 2025-06-29 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='motolom24', max_length=100, verbose_name='Название сайта')),
                ('default_title', models.CharField(blank=True, help_text='Заголовок для страниц без собственного title', max_length=60, verbose_name='Заголовок по умолчанию')),
                ('default_description', models.TextField(blank=True, help_text='Описание для страниц без собственного description', max_length=160, verbose_name='Описание по умолчанию')),
                ('default_keywords', models.CharField(blank=True, help_text='Ключевые слова для страниц без собственных keywords', max_length=255, verbose_name='Ключевые слова по умолчанию')),
                ('google_analytics', models.CharField(blank=True, help_text='G-XXXXXXXXXX или UA-XXXXXXXX-X', max_length=50, verbose_name='Google Analytics ID')),
                ('yandex_metrika', models.CharField(blank=True, help_text='XXXXXXXX', max_length=50, verbose_name='Яндекс.Метрика ID')),
                ('robots_txt', models.TextField(blank=True, help_text='Содержимое файла robots.txt', verbose_name='Robots.txt')),
            ],
            options={
                'verbose_name': 'SEO настройки',
                'verbose_name_plural': 'SEO настройки',
            },
        ),
        migrations.CreateModel(
            name='SEOLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('field_name', models.CharField(max_length=50, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'SEO лог',
                'verbose_name_plural': 'SEO логи',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SEOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=60, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=160, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords')),
                ('h1', models.CharField(blank=True, max_length=100, verbose_name='H1')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO элемент',
                'verbose_name_plural': 'SEO элементы',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
